### ISSUE TITLE
gitgud is not bash compliant

### ISSUE THREAD

**Issue by ArttuKnowit** [Seppohto/OllieOver#1]
Only works for Powershell, can you please make this compliant for a bash shell so I can use it in wsl?

**Comment by ainoelina** [comment]
Agreed, would appreciate functionality in bash as well

**Comment by Seppohto** [comment]
Thanks for this feedback. I have now created gitgud for bash instructions too and you can find it here https://github.com/Seppohto/OllieOver/blob/main/My%20Ultimate%20Git%20Function%20for%20Bash.md
